banner/banners/banner/urls.py
from django.urls import path, include

from .views import (home,
                    eliminar_banner,
                    agregar_editar,
                    listar,
                    )

app_name = 'banner'
urlpatterns = [
    # path('home', home, name='home'),
    path('', listar, name="listar_banners"),
    path('agregar/', agregar_editar, name='banner'),
    path('<int:pk>/', agregar_editar, name='banner_detalle'),
    path('delete/', eliminar_banner, name='eliminar'),

]

banner/banners/pagina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from banner.views import home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('usuarios.urls')),
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('banner/', include('banner.urls')),
    path('popups/', include('popups.urls')),
    path('novedades/', include('novedades.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    # path('usuario/', include('usuarios.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), #vista que te pide el correo
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), #avisa que te mandan correo con un link
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #vista de ingresar contraseña nueva
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banner/banners/banner/models.py
import os
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

# Create your models here.


class Banner(models.Model):
    titulo = models.CharField(max_length=100)
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    fecha_creado = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    imagen = models.ImageField(upload_to='banners')
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()


    #ordenar por calificacion
    #Banner.objects.filter(ratings__isnull=False).order_by('ratings__average')


    def __str__(self):
        return self.titulo

    def extension(self):
        name, extension = os.path.splitext(self.imagen.name)
        return extension


class BannerReview(models.Model):
    RATING_RANGE = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5')
    )
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    banner = models.ForeignKey(Banner, on_delete=models.CASCADE, related_name='rates')
    rating = models.IntegerField(choices=RATING_RANGE,)
    content = models.CharField(max_length=500)
    ratings = GenericRelation(Rating, related_query_name='banners')

    def __str__(self):
        return self.content

banner/banners/banner/forms.py
from django import forms

from .models import Banner


class DateInput(forms.DateInput):
    input_type = 'date'


class BannerForm(forms.ModelForm):
    class Meta:
        model = Banner
        fields = [
            'titulo',
            'imagen',
            'fecha_inicio',
            'fecha_fin',
        ]
        widgets = {
            'titulo': forms.TextInput(attrs={'placeholder': 'Titulo del banner'}),
            'fecha_inicio': DateInput,
            'fecha_fin': DateInput,
        }
        labels = {
            'titulo': 'Titulo Imagen',
            'fecha_inicio': 'Fecha de inicio de publicación',
            'fecha_fin': 'Fecha de fin de publicación',
        }

banner/banners/banner/views.py
import io
import os

from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db.models import Avg
from django.http import JsonResponse
from django.core.files.storage import default_storage
from django.contrib import messages
from django.core.files.uploadedfile import InMemoryUploadedFile

from .models import Banner
from .forms import BannerForm

from popups.models import Popups

from sorl.thumbnail import get_thumbnail

from PIL import Image


def home(request):
    banners = Banner.objects.filter(fecha_inicio__lt=timezone.now(), fecha_fin__gte=timezone.now())
    popups = Popups.objects.filter(fecha_inicio__lt=timezone.now(), fecha_fin__gte=timezone.now())
    return render(
                  request,
                  'home.html',
                  {'banners': banners,
                   'popups': popups,
                  }
    )


@login_required(login_url='/iniciosesion/')
def listar(request):
    return render(request,
                  'lista.html',
                  {'banners': Banner.objects.all()})


# Crear y editar banner
@login_required(login_url='/iniciosesion/')
def agregar_editar(request, pk=None):
    try:
        elemento = Banner.objects.get(pk=pk)
    except Banner.DoesNotExist:
        elemento = None
    if request.POST:
        # acá pregunto si se está editando el elemento, y se coloca una nueva imagen, 
        # se borra la anterior del almacenamiento (solamente funcionaría si hay un solo campo con un archivo)
        if elemento and request.FILES:
            default_storage.delete(elemento.imagen.path)

        form = BannerForm(data=request.POST, files=request.FILES, instance=elemento)
        if form.is_valid():
            # validar si imagen es jpg y no supera determinado tamaño en alto y ancho
            banner = form.save(commit=False)
            extension = banner.extension()
            guardar = False
            if extension == '.jpg':
                guardar = True
                if banner.imagen.width > 1920:
                    guardar = False
                    form.add_error('imagen', "Ancho máximo 1920 px")
                if banner.imagen.height > 500:
                    guardar = False
                    form.add_error(
                        'imagen',
                        "Su imagen tiene %s px de alto. El alto máximo es de 500 px" % banner.imagen.height
                    )
            else:
                form.add_error('imagen', "Extensión inválida. Solo JPG")
            if guardar:
                banner.usuario = request.user
                # banner.save()
                imagen_nueva = convertir_imagen_webp(es_archivo=False, imagen=banner.imagen)
                """ eliminar imagen previa desde el disco """
                default_storage.delete(banner.imagen.path)
                print(banner.imagen.path)
                """ actualizas modelo de datos """
                banner.imagen = imagen_nueva
                banner.save()
                return HttpResponseRedirect(reverse('banner:listar_banners'))
    else:
        form = BannerForm(instance=elemento)
        convertir_carpeta_de_imagenes_a_webp(request, path='media')

    return render(
        request,
        "agregar_editar.html",
        {
            'banners': Banner.objects.all(),
            'form': form,
            'elemento': elemento,
        }
    )


# Eliminar banner
@login_required(login_url='/iniciosesion/')
def eliminar_banner(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            Banner.objects.get(pk=pk).delete()
            mensaje = 'eliminado correctamente'
        except Banner.DoesNotExist:
            mensaje = 'Elemento no encontrado'
    else:
        mensaje = 'No POST'

    return JsonResponse({
        'mensaje': mensaje,
        'url': reverse('banner:listar_banners'),
    })


def convertir_imagen_webp(es_archivo=False, imagen='', path_imagen=''):
    """
    convertir imagen desde archivo o desde upload en WEBP
    :param es_archivo: 
    :param imagen: 
    :return: 
    """

    """ identificar origen: es archivo o es upload? """
    if es_archivo:
        nombre_archivo, ext = os.path.splitext(path_imagen)
        """ abrir imagen """
        im = Image.open(path_imagen).convert("RGB")
        ruta = nombre_archivo + ".webp"
        print(ruta)
        """ convertir imagen """
        im.save(ruta, "WEBP")
        
        return ruta
    else:
        from django.core.files.uploadedfile import InMemoryUploadedFile
        nombre_archivo, ext = os.path.splitext(imagen.name)
        img = Image.open(imagen)
        thumbnailString = io.BytesIO()
        img.save(thumbnailString, 'WEBP')
        ruta = nombre_archivo + ".webp"
        newFile = InMemoryUploadedFile(thumbnailString, None, ruta, 'image/webp', thumbnailString.getbuffer().nbytes, None)
        return newFile



"""
recorrer carpeta usuario
por cada archivo JPG
llamar a la funcion creada para convertir el archivo a WEBP
eliminar archivo JPG
"""
def convertir_carpeta_de_imagenes_a_webp(request, path=''):
    """
    recorre la carpeta del path pasado por parámetro convirtiendo todos los archivos(imágenes)
    jpg a webp que contiene

    :param path: ACLARACIÓN: el path es a partir de la carpeta del proyecto (excluyendo este mismo), 
    es decir, si el proyecto se llama "nimbus" y la carpeta a la que queremos hacer referencia está en:
    nimbus
        media
            BANNERS
    entonces en el path se colocaría: media/banners
    :return: 
    """

    """si el string pasado por parámetro corresponde a un directorio, coloca en la variable
    carpeta una lista con los archivos que posee"""
    directorios_contenidos=[]
    if os.path.isdir(path):
        carpeta = os.listdir(path)
        for item in carpeta:
            """recorre la carpeta"""
            nombre_archivo, ext = os.path.splitext(item)
            """si el archivo es jpg"""
            if ext == '.jpg':
                """se concatena el path con el nombre del archivo, para formar el path del archivo"""
                path_imagen = path+'/'+item
                """se convierte el archivo"""
                nueva = convertir_imagen_webp(es_archivo=True, imagen=item, path_imagen=path_imagen)
                """para borrar el archivo jpg que ya convertimos, formamos el path absoluto para que
                la función lo encuentre"""
                path_completo = "C:\\Users\\usuario\\banner\\banners\\" + path_imagen
                default_storage.delete(path_completo)
            else:
                if ext == "":
                    path_siguiente= path+'/'+nombre_archivo
                    carpeta = os.listdir(path_siguiente)
                    for item in carpeta:
                        directorios_contenidos.append(path_siguiente)
            for dir in directorios_contenidos:
                convertir_carpeta_de_imagenes_a_webp(request=request, path=dir)
                    
                    

        
        #media/novedades/hola.webp
        #thumbnailString = io.BytesIO()
        #item.save(thumbnailString, 'jpg')
        #thumb_file = InMemoryUploadedFile(thumbnailString, None, item, 'image/jpg',
        #                                thumbnailString.getbuffer().nbytes, None)
        #print(thumb_file)
    
    #imagen_archivo = Image.new
    #print(imagen_archivo)
    #im = Image.open(imagen_archivo, 'r')
    #print(im.name)
    
    #imagen = open(imagen.path,)
    #nombre_archivo, ext = os.path.splitext(imagen)
    #if ext == '.jpg':
    #    nueva = convertir_imagen_webp(es_archivo=True, imagen=imagen)
    #    default_storage.delete(imagen_archivo)

        

banner/banners/banner/templates/agregar_editar.html
{% extends "base.html" %}

{% block content %}

<br>
<h1>Banner</h1>
</span>
<br>

<div>
  <form action="{{ request.path }}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Agregar banner</button>
    {% if elemento is not None %}
      <a href="delete/" onClick="return confirm('¿Seguro que quieres borrar el banner {{ elemento.titulo }}?');">Eliminar banner</a>
    {% endif %}
  </form>
</div>

{% endblock content %}

banner/banners/banner/templates/banner.html
{% block content %}

{% load webp_converter %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for banner in banners %}
      <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for banner in banners %}
      <div class="carousel-item {% if forloop.first	%}active{% endif %}">
        <img class="d-block w-100" src="{{ banner.imagen.url }}" alt="First slide">
        {# <img src="{% static_webp '{{ banner.imagen.url }}' 70 %}"> #}
      </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% endblock content %}

banner/banners/banner/templates/lista.html
{% extends "base.html" %}

{% block scripts_encabezado %}

<style>
    .btncerrar{
         color: #FFFFFF;
         background-color: #FF0000;
         background-size: cover;
         background-position: center;
         display: inline-block;
         border: none;
<!--         padding: 10px;-->
         padding-bottom:15px;
         width: 100px;
         border-radius: 500px;
         height: 30px;
         transition: all 0.5s;
         cursor: pointer;
    }
    .btncerrar:hover
    {
         width: 150px;
         height: 35px;
    }
</style>

{% endblock %}

{% block content %}

<div class="text-center">
    <br>
    <h5>Banners cargados</h5>
    <a href="/banner/agregar/">Agregar nuevo</a>
</div>

<br>
<div class="container; text-center">
    {% for banner in banners %}
    <div class="row">
        <div class="col-sm">
            <img class="d-block w-100" src="{{ banner.imagen.url }}" alt="Imagen">
        </div>
        <div class="col-sm">
            {{ banner.titulo }}
            {{ banner.ratings }}
        </div>
        <div class="col-sm">
            <a class="btn btn-primary" href="/banner/{{ banner.pk }}/">Editar</a>
            <button class="btn btn-danger eliminar" data-pk="{{ banner.pk }}">Eliminar</button>
        </div>
        <br>
    </div>
    <br>
    {% endfor %}
</div>

{% endblock content %}

{% block scripts_pie %}
<script type="text/javascript">
(function($) {
    'use strict';
    $('.eliminar').on('click', function() {
        var pk = $(this).data('pk');
        $.ajax({
            method: "POST",
            url: "{% url 'banner:eliminar' %}",
            data: { pk: pk, csrfmiddlewaretoken: '{{ csrf_token }}' }
        })
        .done(function( datos ) {
            console.log(datos);
            //datos.mensaje;
            //datos.url;
            alert(datos.mensaje);
            location.reload();
        })
        .fail(function( jqXHR, textStatus ) {
            alert('Oops!!', 'Encontramos un problema: ' + jqXHR + ' estado: ' + textStatus, 'danger');
        });
    });
})(jQuery);
</script>
{% endblock %}

banner/banners/banner/templates/rating.html
{% for banner in banners %}
   <div data-marker-id="59c0c8e33b1527bfe2abaf92" class="col-sm-6 col-xl-4 mb-5">
        <div class="card h-100 border-0 shadow">
             <div style="background-image: {{ banner.imagen.url }}; min-height: 200px;"
                                 class="card-img-top overflow-hidden dark-overlay bg-cover">
                 {# <a href="{% url 'gig-detail' banner.id %}" class="tile-link"></a>#}
                    <div class="card-img-overlay-bottom z-index-20"></div>
                    <div class="card-img-overlay-top d-flex justify-content-between align-items-center">
<!--                    <div class="badge badge-transparent badge-pill px-3 py-2">{{ git.category }}</div>-->
                     <a href="javascript: void();" class="card-fav-icon position-relative z-index-40">
                      <svg class="svg-icon text-white">
                                            <use xlink:href="#heart-1"></use>
                                        </svg>
                                    </a>
                   </div>
                </div>
                <div class="card-body">
                    {% comment %}
<!--                     <h6 class="text-shadow"><a href="{% url 'gig-detail' gig.id %}"-->
<!--                                                           style="text-decoration: none; color: black">-->
                    {% endcomment %}
                                    {{ banner.titulo }}</a></h6>
                                <p class="mb-2 text-xs" id="stars">
                                    {{ banner.avg_review }}
                                    {% if banner.avg_review is not None %}
                                        {{ banner.avg_review }}
                                    {% endif %}
                                    <i class="fa fa-star text-warning"></i>
                                    <i class="fa fa-star text-warning"></i>
                                    <i class="fa fa-star text-warning"></i>
                                    <i class="fa fa-star text-warning"></i>
                                    <i class="fa fa-star text-gray-300"></i>
                                </p>
<!--                                <p class="text-sm text-muted mb-3">{{ gig.description|slice:"20" }}...</p>-->
                                <p class="text-sm text-muted text-uppercase mb-1">
                                   {# <span>By <a href="{% url 'profile' gig.user.username %}"#}
                                                class="text-dark">{{ banner.usuario }}</a></span>
                                    <span class="float-right"><b class="text-shadow text-lg"
<!--                                                                 style="color: black;">${{ gig.price }}</b></span>-->
                                </p>
                            </div>
                        </div>
                    </div>
<fieldset class="starability-result mx-auto" data-rating="{{ banner.avg_review }}">
    Rated: {{ banner.avg_review }} stars
</fieldset>
                {% endfor %}