banner/banners/banner/urls.py
from django.urls import path, include

from .views import (home,
                    eliminar_banner,
                    agregar_editar,
                    listar,
                    )

app_name = 'banner'
urlpatterns = [
    # path('home', home, name='home'),
    path('', listar, name="listar_banners"),
    path('agregar/', agregar_editar, name='banner'),
    path('<int:pk>/', agregar_editar, name='banner_detalle'),
    path('delete/', eliminar_banner, name='eliminar'),

]

banner/banners/novedades/urls.py
from django.urls import path

from .views import (
                    eliminar_novedad,
                    agregar_editar,
                    listar,
                    detalle,
                    )
app_name = 'novedades'
urlpatterns = [
    path('', listar, name="listar_novedades"),
    path('<int:pk>/', agregar_editar, name='novedad_editar'),
    path('agregar/', agregar_editar, name='novedad_agregar'),
    path('<int:pk>/ver/', detalle, name='novedad_detalle'),
    path('delete/', eliminar_novedad, name='eliminar'),
]

banner/banners/pagina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from banner.views import home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('usuarios.urls')),
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('banner/', include('banner.urls')),
    path('popups/', include('popups.urls')),
    path('novedades/', include('novedades.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    # path('usuario/', include('usuarios.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), #vista que te pide el correo
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), #avisa que te mandan correo con un link
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #vista de ingresar contraseña nueva
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banner/banners/novedades/models.py
import os

from django.db import models
from star_ratings.models import Foo

# Create your models here.


class Novedad(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200)
    contenido = models.CharField(max_length=10000)
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    fecha_creado = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    imagen = models.ImageField(upload_to='novedades')
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
    youtube_url = models.CharField(null=True, blank=True, max_length=255)
    youtube_video_id = models.CharField(null=True, blank=True, max_length=255)
    estrellas = models.ForeignKey(Foo, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.titulo

    def extension(self):
        name, extension = os.path.splitext(self.imagen.name)
        return extension

#    def save(self, *args, **kwargs):
#        aux = self.youtube
#        if aux.find('/') > 0:
#            aux = self.youtube.split('/')
#            aux = aux[-1:]
#            self.youtube = aux[0]
#        super(Novedad, self).save(*args, **kwargs)

banner/banners/novedades/forms.py
from django import forms

from .models import Novedad


class DateInput(forms.DateInput):
    input_type = 'date'


class NovedadForm(forms.ModelForm):

    class Meta:
        model = Novedad
        fields = [
            'titulo',
            'descripcion',
            'imagen',
            'youtube_url',
            'fecha_inicio',
            'fecha_fin',
        ]
        widgets = {
            'titulo': forms.TextInput(attrs={'placeholder': 'Titulo de novedad'}),
            'fecha_inicio': DateInput,
            'fecha_fin': DateInput,
            'youtube_url': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'titulo': 'Titulo Imagen',
            'fecha_inicio': 'Fecha de inicio de publicación',
            'fecha_fin': 'Fecha de fin de publicación',
            'youtube_url': 'Video de Youtube (link)',
        }

banner/banners/novedades/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import JsonResponse
from urllib.parse import urlparse
import re

from .models import Novedad
from .forms import NovedadForm

from star_ratings.models import Foo


def obtener_id_video(link):
    """
    Lo que hace es encontrar el ID del video de youtube para que luego se muestre en la página correctamente. 
   
    :param link: Tipo: string. URL del video de youtube que se quiera mostrar.
    :return: Tipo diccionario: -id correspondiente al video, -mensaje de error, -correcto en verdadero si se encontró el ID.
    """
    diccionario = {
        'id': '', 
        'mensaje': '', 
        'correcto': False
    }
    
    # esta exp regular va a verificar si el link del video cumple con el formato de youtube
    expresion_regular = "^((?:https?:)?\/\/)?((?:www|m)\.)?((?:youtube\.com|youtu.be))(\/(?:[\w\-]+\?v=|embed\/|v\/)?)([\w\-]+)(\S+)?$"
    
    # re.search busca la cadena del segundo parametro en la exp regular, si no lo encuentra, devuelve None.
    # Que se encuentre el link en la exp reg no significa que el link sea válido. Para verificar si
    # existe este video, habría que hacer cierta conexión a youtube
    match = re.search(expresion_regular, link)
    if match is not None:
        # exp_reg_ID es una expresion para encontrar el ID del video
        exp_reg_ID = "((?<=(v|V)/)|(?<=be/)|(?<=(\?|\&)v=)|(?<=embed/))([\w-]+)"
            
        # re.findall devuelve en una lista con una tupla de los strings que coinciden en la exp regular
        lo_que_encontro = re.findall(exp_reg_ID, link)
        for lista in lo_que_encontro:
            for item in lista:
                if len(item) > 1:
                    diccionario['id'] = item
                    diccionario['correcto'] = True
    else:
        diccionario['mensaje'] = 'Link incorrecto'

    return diccionario



def detalle(request,pk):

    return render(
        request,
        'home_copy.html',
        {
            'novedad': Novedad.objects.get(pk=pk),
            'object': (Novedad.objects.get(pk=pk)).estrellas,
        }
    )


def listar(request):
    novedades = Novedad.objects.filter(fecha_inicio__lt=timezone.now(), fecha_fin__gte=timezone.now())
    return render(
        request,
        'lista_novedades.html',
        {'novedades': novedades}
    )


@login_required
def agregar_editar(request, pk=0):
    if pk == 0:
        elemento = None
    else:
        try:
            elemento = Novedad.objects.get(pk=pk)
        except Novedad.DoesNotExist:
            mensaje = 'el elemento solicitado no existe'
            # return HttpResponseRedirect('/novedades/')
            return HttpResponseRedirect(reverse('novedades'))
    if request.POST:
        form = NovedadForm(data=request.POST, files=request.FILES, instance=elemento)
        if form.is_valid():
            # validar si imagen es jpg y no supera determinado tamaño en alto y ancho
            novedad = form.save(commit=False)
            extension = novedad.extension()
            guardar = False
            if extension == '.jpg':
                #guardar = True
                # if banner.imagen.width > 1920:
                #     guardar = False
                #     form.add_error('imagen', "Ancho máximo 1920 px")
                # if banner.imagen.height > 500:
                #     guardar = False
                #     form.add_error(
                #         'imagen',
                #         "Su imagen tiene %s px de alto. El alto máximo es de 500 px" % banner.imagen.height
                #     )
                if novedad.youtube_url != None and novedad.youtube_url != '':
                    obtener_id = obtener_id_video(novedad.youtube_url)
                    if obtener_id['correcto']:
                        novedad.youtube_video_id = obtener_id['id']
                        guardar = True
                    else:
                        form.add_error('youtube_url', obtener_id['mensaje'])
                else:
                    novedad.youtube_video_id = ""
                    guardar = True
            else:
                form.add_error('imagen', "Extensión inválida. Solo JPG")
            
            if guardar:
                novedad.usuario = request.user
                obj, created = Foo.objects.get_or_create(bar='Rating de '+novedad.titulo)
                novedad.estrellas = obj
                novedad.save()
                #return HttpResponseRedirect('/novedades/')

    else:
        form = NovedadForm(instance=elemento)

    return render(
        request,
        "agregar_editar_novedad.html",
        {
            'banners': Novedad.objects.all(),
            'form': form,
            'elemento': elemento,
        }
    )


# Eliminar banner
@login_required(login_url='/iniciosesion/')
def eliminar_novedad(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            Novedad.objects.get(pk=pk).delete()
            mensaje = 'eliminado correctamente'
        except Novedad.DoesNotExist:
            mensaje = 'Elemento no encontrado'
    else:
        mensaje = 'No POST'

    return JsonResponse({
        'mensaje': mensaje,
        'url': reverse('novedades:listar_novedades'),
    })

banner/banners/novedades/templates/agregar_editar_novedad.html
{% extends "base.html" %}

<script>
  .centrar-form{
 margin: 50px auto;
 float:none;
}
</script>

{% block content %}
<div  class="centrar-form">
  <br>
  <h1>Novedad</h1>
  </span>
  <br>

  <div>
    <form action="{{ request.path }}" method="POST" enctype="multipart/form-data">{% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <button type="submit">Agregar novedad</button>
      {% if elemento is not None %}
        <a href="delete/" onClick="return confirm('¿Seguro que quieres borrar el banner {{ elemento.titulo }}?');">Eliminar novedad</a>
      {% endif %}
    </form>
  </div>
</div>

{% endblock content %}

banner/banners/novedades/templates/lista_novedades.html
{% extends "base.html" %}

{% block scripts_encabezado %}

<style>
    .btncerrar{
         color: #FFFFFF;
         background-color: #FF0000;
         background-size: cover;
         background-position: center;
         display: inline-block;
         border: none;
<!--         padding: 10px;-->
         padding-bottom:15px;
         width: 100px;
         border-radius: 500px;
         height: 30px;
         transition: all 0.5s;
         cursor: pointer;
    }
    .btncerrar:hover
    {
         width: 150px;
         height: 35px;
    }
</style>

{% endblock %}

{% block content %}

<div class="text-center">
    <br>
    <h5>NOVEDADES</h5>
    {% if request.user.is_authenticated %}
        <a href="/novedades/agregar/">Agregar nueva novedad</a>
    {% endif %}
</div>

<br>
<div class="container; text-center">
    {% for novedad in novedades %}
        <div class="row">
            <div class="col-sm">
                <img class="d-block w-100" src="{{ novedad.imagen.url }}" alt="Imagen">
                <br>
            </div>
            <div class="col-sm">
                <strong>{{ novedad.titulo }}</strong>
                <br>
                {{ novedad.descripcion }}
            </div>
            <div class="col-sm">
            {% if request.user.is_authenticated %}
                <br>
                <button class="btn btn-danger eliminar" data-pk="{{ novedad.pk }}">Eliminar</button>
                <br>
                <br>
                <br>
                <a href="/novedades/{{ novedad.pk }}/">Editar</a>
                <br>

                
            {% endif %}
            <br>

                <a href="/novedades/{{ novedad.pk }}/ver/">VER</a>
                <br>
            </div>


            <br>
        </div>
    {% endfor %}
</div>

{% endblock content %}

{% block scripts_pie %}
<script type="text/javascript">
(function($) {
    'use strict';
    $('.eliminar').on('click', function() {
        var pk = $(this).data('pk');
        $.ajax({
            method: "POST",
            url: "{% url 'novedades:eliminar' %}",
            data: { pk: pk, csrfmiddlewaretoken: '{{ csrf_token }}' }
        })
        .done(function( datos ) {
            console.log(datos);
            //datos.mensaje;
            //datos.url;
            alert(datos.mensaje);
            location.reload();
        })
        .fail(function( jqXHR, textStatus ) {
            alert('Oops!!', 'Encontramos un problema: ' + jqXHR + ' estado: ' + textStatus, 'danger');
        });
    });
})(jQuery);
</script>
{% endblock %}

banner/banners/novedades/templates/novedad.html
{% extends "base.html" %}
{% load ratings %}

{% block content %}

<div class="row">
    <div class="col-sm text-center">
        <strong>{{ novedad.titulo }}</strong>
        <br>
        {{ novedad.descripcion }}
        <br>
        <img class="d-block w-100" src="{{ novedad.imagen.url }}" alt="Imagen">
        <br>
        {{ novedad.contenido }}
        <br>
        {% block star %}
        {% endblock %}
        <br>
        {% if novedad.youtube_video_id %}
        <iframe width="944" height="500" src="http://www.youtube.com/embed/{{ novedad.youtube_video_id }}" 
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; 
            gyroscope; picture-in-picture" allowfullscreen>
        </iframe>
        {% endif %}
    </div>
</div>

{% endblock content %}