banner/banners/banner/urls.py
from django.urls import path, include

from .views import (home,
                    eliminar_banner,
                    agregar_editar,
                    listar,
                    )

app_name = 'banner'
urlpatterns = [
    # path('home', home, name='home'),
    path('', listar, name="listar_banners"),
    path('agregar/', agregar_editar, name='banner'),
    path('<int:pk>/', agregar_editar, name='banner_detalle'),
    path('delete/', eliminar_banner, name='eliminar'),

]

banner/banners/pagina/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from banner.views import home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('usuarios.urls')),
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('banner/', include('banner.urls')),
    path('popups/', include('popups.urls')),
    path('novedades/', include('novedades.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    # path('usuario/', include('usuarios.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), #vista que te pide el correo
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), #avisa que te mandan correo con un link
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #vista de ingresar contraseña nueva
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banner/banners/popups/urls.py
from django.urls import path

from .views import (
                    popup,
                    eliminar_popup,
                    agregar_editar,
                    listar_popup,
                    )
app_name = 'popups'
urlpatterns = [
    path('', listar_popup, name='lista_popups'),
    path('agregar/', agregar_editar, name='popup'),
    path('<int:pk>/', agregar_editar, name='popup_detalle'),
    path('delete/', eliminar_popup, name='eliminar'),
]

banner/banners/popups/models.py
import os
from django.db import models

# Create your models here.


class Popups(models.Model):
    titulo = models.CharField(max_length=100)
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    fecha_creado = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    imagen = models.ImageField(upload_to='popups')
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()

    def __str__(self):
        return self.titulo

    def extension(self):
        name, extension = os.path.splitext(self.imagen.name)
        return extension

banner/banners/popups/forms.py
from django import forms

from .models import Popups


class DateInput(forms.DateInput):
    input_type = 'date'


class PopupForm(forms.ModelForm):

    class Meta:
        model = Popups
        fields = [
            'titulo',
            'imagen',
            'fecha_inicio',
            'fecha_fin',
        ]
        widgets = {
            'titulo': forms.TextInput(attrs={'placeholder': 'Titulo del Pop up'}),
            'fecha_inicio': DateInput,
            'fecha_fin': DateInput,
        }
        labels = {
            'titulo': 'Titulo Imagen',
            'fecha_inicio': 'Fecha de inicio de publicación',
            'fecha_fin': 'Fecha de fin de publicación',
        }

banner/banners/popups/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from .models import Popups
from .forms import PopupForm
from banner.views import convertir_imagen_webp


def popup(request):
    popups = Popups.objects.filter(fecha_inicio__lt=timezone.now(), fecha_fin__gte=timezone.now())
    return render(
        request,
        'Popup.html',
        {'popups': popups}
    )


@login_required(login_url='/iniciosesion/')
def listar_popup(request):

    return render(
        request,
        'lista_popups.html',
        {'popups': Popups.objects.all()}
    )


@login_required(login_url='/iniciosesion/')
# Crear y editar banner
def agregar_editar(request, pk=None):
    try:
        elemento = Popups.objects.get(pk=pk)
    except Popups.DoesNotExist:
        elemento = None
    if request.POST:
        form = PopupForm(data=request.POST, files=request.FILES, instance=elemento)
        if form.is_valid():
            # validar si imagen es jpg y no supera determinado tamaño en alto y ancho
            popup = form.save(commit=False)
            extension = popup.extension()
            guardar = False
            if extension == '.jpg':
                guardar = True
                #if popup.imagen.width > 1920:
                #    guardar = False
                #    form.add_error('imagen', "Ancho máximo 1920 px")
                #if popup.imagen.height > 500:
                #    guardar = False
                #    form.add_error(
                #        'imagen',
                #        "Su imagen tiene %s px de alto. El alto máximo es de 500 px" % popup.imagen.height
                #    )
            else:
                form.add_error('imagen', "Extensión inválida. Solo JPG")
            if guardar:
                popup.usuario = request.user
                popup.save()
                convertir_imagen_webp(es_archivo=True, imagen=popup.imagen)
                return HttpResponseRedirect('/popups/')

    else:
        form = PopupForm(instance=elemento)

    return render(
        request,
        "agregar_editar_popup.html",
        {
            'popups': Popups.objects.all(),
            'form': form,
            'elemento': elemento,
        }
    )


# Eliminar banner
@login_required(login_url='/iniciosesion/')
def eliminar_popup(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            Popups.objects.get(pk=pk).delete()
            mensaje = 'eliminado correctamente'
        except Popups.DoesNotExist:
            mensaje = 'Elemento no encontrado'
    else:
        mensaje = 'No POST'

    return JsonResponse({
        'mensaje': mensaje,
        'url': reverse('popups:lista_popups'),
    })

banner/banners/popups/templates/Popup.html
{% block content %}
<!-- Button trigger modal-->
<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">-->
<!--  Launch demo modal-->
<!--</button>-->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">POP UPS!!!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">


          <div id="carouselPopup" class="carousel slide" data-ride="carousel">
              <ol class="carousel-indicators">
                {% for popup in popups %}
                  <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                {% endfor %}
              </ol>
              <div class="carousel-inner">
                {% for popup in popups %}
                  <div class="carousel-item {% if forloop.first	%}active{% endif %}">
                    <img class="d-block w-100" src="{{ popup.imagen.url }}" alt="First slide">
                  </div>
                {% endfor %}
              </div>
              <a class="carousel-control-prev" href="#carouselPopup" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselPopup" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
          </div>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
<!--        <button type="button" class="btn btn-primary">Save changes</button>-->
      </div>
    </div>
  </div>
</div>
{% endblock content %}

banner/banners/popups/templates/agregar_editar_popup.html
{% extends "base.html" %}

{% block content %}

<br>
<h1>Pop Up</h1>
</span>
<br>

<div>
  <form action="{{ request.path }}" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Agregar Pop up</button>
    {% if elemento is not None %}
      <a href="delete/" onClick="return confirm('¿Seguro que quieres borrar el pop up {{ elemento.titulo }}?');">Eliminar Pop Up</a>
    {% endif %}
  </form>
</div>

{% endblock content %}

banner/banners/popups/templates/lista_popups.html
{% extends "base.html" %}

{% block content %}

<style>
    .btncerrar{
         color: #FFFFFF;
         background-color: #FF0000;
         background-size: cover;
         background-position: center;
         display: inline-block;
         border: none;
<!--         padding: 10px;-->
         padding-bottom:15px;
         width: 100px;
         border-radius: 500px;
         height: 30px;
         transition: all 0.5s;
         cursor: pointer;
    }
    .btncerrar:hover
    {
         width: 150px;
         height: 35px;
    }
</style>


<div class="text-center">
    <br>
    <h5>Pop Ups cargados</h5>
    <a href="/popups/agregar/">Agregar nuevo</a>
</div>

<br>
<div class="container; text-center">
    {% for popup in popups %}
    <div class="row">
        <div class="col-sm">
            <img class="d-block w-100" src="{{ popup.imagen.url }}" alt="Imagen">
            <br>
        </div>
        <div class="col-sm">
            {{ popup.titulo }}
        </div>
        <div class="col-sm">
            <a href="/popups/{{ popup.pk }}/">Editar</a>
            <br>
            <button class="btn btn-danger eliminar" data-pk="{{ popup.pk }}">Eliminar</button>
        </div>
        <br>
    </div>
    {% endfor %}
</div>

{% endblock content %}

{% block scripts_pie %}
<script type="text/javascript">
(function($) {
    'use strict';
    $('.eliminar').on('click', function() {
        var pk = $(this).data('pk');
        $.ajax({
            method: "POST",
            url: "{% url 'popups:eliminar' %}",
            data: { pk: pk, csrfmiddlewaretoken: '{{ csrf_token }}' }
        })
        .done(function( datos ) {
            console.log(datos);
            //datos.mensaje;
            //datos.url;
            alert(datos.mensaje);
            location.reload();
        })
        .fail(function( jqXHR, textStatus ) {
            alert('Oops!!', 'Encontramos un problema: ' + jqXHR + ' estado: ' + textStatus, 'danger');
        });
    });
})(jQuery);
</script>
{% endblock %}